### ISSUE TITLE
Nginx error

### ISSUE THREAD

**Issue by skawr** [cortez24rus/xui-reverse-proxy#10]
pub   rsa4096 2024-05-29 [SC]
      8540A6F18833A80E9C1653A42FD21310B49F6B46
uid                      nginx signing key <signing-key-2@nginx.com>

pub   rsa2048 2011-08-19 [SC] [expires: 2027-05-24]
      573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
uid                      nginx signing key <signing-key@nginx.com>

pub   rsa4096 2024-05-29 [SC]
      9E9BE90EACBCDE69FE9B204CBCDCD8A38D88A2B3
uid                      nginx signing key <signing-key-3@nginx.com>

deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu jammy nginx
Package: *
Pin: origin nginx.org
Pin: release o=nginx
Pin-Priority: 900

Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Get:2 http://nginx.org/packages/ubuntu jammy InRelease [3,599 B]
Hit:3 http://cdn.archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://cdn.archive.ubuntu.com/ubuntu jammy-updates InRelease
Get:5 http://nginx.org/packages/ubuntu jammy/nginx amd64 Packages [24.4 kB]
Hit:6 http://cdn.archive.ubuntu.com/ubuntu jammy-backports InRelease
Fetched 28.0 kB in 1s (35.4 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package nginx-module-ssl
E: Unable to locate package nginx-module-http2
E: Unable to locate package nginx-module-proxy
E: Unable to locate package nginx-module-rewrite
E: Unable to locate package nginx-module-gzip
E: Unable to locate package nginx-module-websocket
E: Unable to locate package nginx-module-fastcgi
E: Unable to locate package nginx-module-limit-req
E: Unable to locate package nginx-module-limit-conn
E: Unable to locate package nginx-module-stream
E: Unable to locate package nginx-module-security
E: Unable to locate package nginx-module-upstream
E: Unable to locate package systemd-resolved

_____________________________________________________

[?]  Настройка NGINX 
/dev/fd/63: line 641: /etc/nginx/conf.d/local.conf: No such file or directory
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://cdn.archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://cdn.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://nginx.org/packages/ubuntu jammy InRelease
Hit:5 http://cdn.archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
zip is already the newest version (3.0-12build2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[?]  Random template name: techking-free-html5-template-for-corporate-business 
[!]  Extraction error! 
/dev/fd/63: line 552: nginx: command not found

**Comment by cortez24rus** [comment]
thx, fix
