### ISSUE TITLE
ошибки

### ISSUE THREAD

**Issue by Alexx392** [cortez24rus/xui-reverse-proxy#12]
Приветствую!
Решил попробовать новые функции, но столкнулся с рядом ошибок:

1. Generating a random website не работает, завершается ошибкой, путь не найден. В ручную конечно можно поставить, но...
2. сразу после установки, если попробовать перезапустить xray
![4K # (7)](https://github.com/user-attachments/assets/d0b5999f-2c46-48c4-8d3c-cca8925d9836)
В дальнейшем пробовал настроить с этой ошибкой, но на каком-то этапе пропадает доступ к панели
3. если отключить подключения, то доступ к панели пропадает вообще 
![Снимтмок](https://github.com/user-attachments/assets/5c8730c9-95be-4a7b-8269-cd23c9161830)

**Comment by cortez24rus** [comment]
1. Поправил, у многих и так работало, не ясно до конца, что у вас пошло не так.
2. Взял на заметку, проверю.
3. Завязано все на этих инбаундах:
если отключить xtls, то перестает работать редирект с www.example.com > example.com
если отключить steal, то перестанет работать вся панель, в связи с тем, что маршрут на сервере идет по такому принципу (443 nginx upsteam > 7443 inbound steal > 36076 nginx panel), то есть отключая промежуточное звено в виде инбаунда, вы отключаете панель в том числе. Это можно решить раскомментировав строку web в /etc/nginx/stream-enable/stream.conf и nginx -s reload
