### ISSUE TITLE
Adguard home login error

### ISSUE THREAD

**Issue by xPROMSx** [cortez24rus/xui-reverse-proxy#15]
После полной установки и настройки не заходит в панель adguard home с нижеприведенной ошибкой. Логин от панели (заданный при установке) или admin/admin вызывают ошибку. 
![IMG_0446](https://github.com/user-attachments/assets/8cf399c0-bd3d-4e18-a4a8-bb325bf9bb74)

Система - свежеустановленная и обновленная ubuntu 24.04. 
Все остальное работает без нареканий.

**Comment by cortez24rus** [comment]
Внесены соответствующие правки
