### ISSUE TITLE
open web adguard home error

### ISSUE THREAD

**Issue by Vancltkin** [cortez24rus/xui-reverse-proxy#20]
![{A577382E-04EB-4AE1-9612-A43C2C86B753}](https://github.com/user-attachments/assets/5c41d6f1-aba3-4de1-91e7-8aa48f1495cb)

**Comment by Vancltkin** [comment]
Ставил 1.3.0

**Comment by cortez24rus** [comment]
![image](https://github.com/user-attachments/assets/f13480af-d3c7-42e4-b3cb-93e905f53595)
Только что установил, входит без проблем. Предлагаю посмотреть по сути изменены ли логи и пароль /root/AdGuardHome/AdGuardHome.yaml.

Не информативная ошибка.

**Comment by Vancltkin** [comment]
- name: username
    password: hash
    
    так установилось

**Comment by Vancltkin** [comment]
> ![image](https://private-user-images.githubusercontent.com/89983388/395875552-f13480af-d3c7-42e4-b3cb-93e905f53595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNzk1NjQsIm5iZiI6MTczNDI3OTI2NCwicGF0aCI6Ii84OTk4MzM4OC8zOTU4NzU1NTItZjEzNDgwYWYtZDNjNy00MmU0LWIzY2ItOTNlOTA1ZjUzNTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDE2MTQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NjlkMThkOGM5YzMwMjA3MWU0OGJiNmMyYmYyYmMzMTgyYzgyZjVjMjc3YWI0Zjc3ZmE5NjNhODk2Y2M5ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rHVdzawAPeXwAMc3Aez9gHLgm90jRHVVLKMCTmKKyBg) Предлагаю посмотреть изменены ли логин и пароль /root/AdGuardHome/AdGuardHome.yaml.
> 
> Вход в веб https://example.com/path/login.html
> 
> Не информативная ошибка.

name: username
password: hash

так установилось

**Comment by cortez24rus** [comment]
Какая ОС?

**Comment by cortez24rus** [comment]
Так как установка прошла, а запускать снова думаю желания нет, то сделайте следующее
htpasswd -B -C 10 -n -b username password | cut -d ":" -f 2
полученный HASH введи в поле password: HASH, как и логин

после перезагрузка
/root/AdGuardHome/AdGuardHome -s restart

**Comment by Vancltkin** [comment]
> Какая ОС?

Ubuntu 24

у меня 4 сервера на 3 не установился этот параметр, а на другой установился , я просто из одной в другие скопировал данный логин и ключ и ворк

**Comment by Vancltkin** [comment]
> Какая ОС?

Сервер на котором установилось нормально Ubuntu 22 , а на других Ubuntu 24
